### ISSUE TITLE
Can not install Package Cloud9 CLI

### ISSUE THREAD

**Issue by matzeeable** [c9/install#99]
Hi there,

I am a c9.io user since years and now I want to migrate to AWS: Since hours I am trying to get the AWS Cloud9 running through SSH to my DigitalOcean droplet. Unfortunely I always get this error while installing C9 CLI:

```
cat /root/.c9/empty/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/root/.c9/node/bin/node',
1 verbose cli   '/root/.c9/node/bin/npm',
1 verbose cli   'explore',
1 verbose cli   '-g',
1 verbose cli   'c9',
1 verbose cli   '--',
1 verbose cli   'ln -sfv $(pwd)/bin/* /usr/bin/' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose stack Error: spawn ENOENT
4 verbose stack     at ChildProcess.<anonymous> (/root/.c9/node/lib/node_modules/npm/lib/utils/spawn.js:33:16)
4 verbose stack     at emitTwo (events.js:106:13)
4 verbose stack     at ChildProcess.emit (events.js:191:7)
4 verbose stack     at maybeClose (internal/child_process.js:852:16)
4 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
5 verbose cwd /root/.c9/empty
6 error Linux 4.15.0-42-generic
7 error argv "/root/.c9/node/bin/node" "/root/.c9/node/bin/npm" "explore" "-g" "c9" "--" "ln -sfv $(pwd)/bin/* /usr/bin/"
8 error node v6.3.1
9 error npm  v3.10.3
10 error file /bin/bash
11 error code ENOENT
12 error errno ENOENT
13 error syscall spawn
14 error enoent spawn ENOENT
15 error enoent spawn ENOENT
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
15 error enoent
15 error enoent Check if the file '/bin/bash' is present.
16 verbose exit [ 1, true ]
```

![](https://i.imgur.com/dklAd6E.png)

My installations:
```
$ which node
/root/.nvm/versions/node/v11.5.0/bin/node
$ node --version
v11.5.0
$ npm --version
6.4.1
$ python --version
Python 2.7.15rc1
```

I have installed node with NVM. But also tried with `apt-get` but the problem persists. Also, I tried to recreate the complete workspace. Another try was to install the `c9/install` .sh script directly but then I get the following error:

```
Couldn't load node modules sqlite3 and sequelize from /root/.c9/node_modules node version: v6.3.1; node execPath /root/.c9/node/bin/node Error: Cannot find module '/root/.c9/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node' Error: Cannot find module '/root/.c9/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
AWS Cloud9 detected you are missing one or more collab dependencies. Would you like to open the installer to update to the latest version?
```

I have also searched the forum and found similar questions but unfortunely no answer:
- https://forums.aws.amazon.com/thread.jspa?threadID=287868
- https://forums.aws.amazon.com/thread.jspa?threadID=287681
- https://forums.aws.amazon.com/thread.jspa?threadID=288561
- https://forums.aws.amazon.com/thread.jspa?threadID=287964
- https://forums.aws.amazon.com/thread.jspa?threadID=287681

AWS Forum Reference - sorry for double posting, but I do not exactly know what is the correct destination for this question: https://forums.aws.amazon.com/thread.jspa?threadID=295600

Best regards,
Matthew :-)

**Comment by matzeeable** [comment]
I have successfully established a SSH connection to my own server. I have also published a short tutorial for this: https://matthias-web.com/2018/12/21/how-to-use-aws-cloud9-ide-with-digitalocean-droplet/ Perhaps this is interesting for other users, too.
